@extends('layouts.app')

@section('title', 'Payments')

@section('content')
@php
    $currency = \App\Models\Setting::value('currency', '₹');
    $summaryValues = $subscriptionSummaries->values();
    $totalOutstanding = $summaryValues->sum('balance_amount');
    $partialCount = $summaryValues->where('payment_status', 'partial')->count();
    $overdueCount = $summaryValues->where('is_expired', true)->where('balance_amount', '>', 0)->count();
@endphp
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><h1 class="page-title mb-0">Payment ledger</h1><p class="page-subtitle">Every receipt is preserved as a traceable transaction.</p></div>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPayment"><i class="bi bi-plus-lg me-1"></i>Record payment</button>
</div>

@if(session('receipt_ids'))<div class="alert alert-success d-flex flex-wrap justify-content-between align-items-center gap-2"><div><strong><i class="bi bi-check-circle me-1"></i>Payment saved successfully.</strong><div class="small">Each allocated transaction has its own receipt.</div></div><div class="d-flex flex-wrap gap-2">@foreach(session('receipt_ids') as $receiptId)<a class="btn btn-sm btn-success" target="_blank" href="{{ route('payments.receipt.print',$receiptId) }}"><i class="bi bi-printer me-1"></i>Print Receipt{{ count(session('receipt_ids'))>1?' #'.$loop->iteration:'' }}</a>@endforeach</div></div>@endif

<div class="row g-3 mb-4">
    <div class="col-6 col-lg-3"><div class="card metric-card"><div class="card-body"><div class="metric-label">Outstanding amount</div><div class="metric-value">{{ $currency }}{{ number_format($totalOutstanding, 2) }}</div></div></div></div>
    <div class="col-6 col-lg-3"><div class="card metric-card"><div class="card-body"><div class="metric-label">Awaiting payment</div><div class="metric-value">{{ $summaryValues->whereIn('payment_status', ['pending','partial'])->count() }}</div></div></div></div>
    <div class="col-6 col-lg-3"><div class="card metric-card"><div class="card-body"><div class="metric-label">Partial payments</div><div class="metric-value">{{ $partialCount }}</div></div></div></div>
    <div class="col-6 col-lg-3"><div class="card metric-card"><div class="card-body"><div class="metric-label">Expired & unpaid</div><div class="metric-value text-danger">{{ $overdueCount }}</div></div></div></div>
</div>

<div class="card mb-4"><div class="card-body"><form class="d-flex flex-wrap align-items-center gap-2"><input name="search" class="form-control flex-grow-1" style="min-width:220px" value="{{ request('search') }}" placeholder="Search customer, mobile, or receipt"><div class="form-check form-switch mx-2"><input class="form-check-input" type="checkbox" name="show_paid" value="1" id="showPaid" @checked(request()->boolean('show_paid')) onchange="this.form.submit()"><label class="form-check-label text-nowrap" for="showPaid">Show paid subscription accounts</label></div><button class="btn btn-dark px-4">Search</button><a href="{{ route('payments.index') }}" class="btn btn-light"><i class="bi bi-x-circle me-1"></i>Clear</a></form><div class="small text-muted mt-2">This switch controls the paid-account review list and the Record payment customer search. The transaction ledger below always shows recorded receipts.</div></div></div>

@if(request()->boolean('show_paid'))
<div class="card mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><div><strong>Paid subscription accounts</strong><div class="small text-muted">Completed subscriptions shown for review only.</div></div><span class="badge status-paid">{{ $paidSubscriptions->count() }} paid</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Customer</th><th>Subscription</th><th>Period</th><th>Package</th><th class="text-end">Paid</th><th class="text-end">Balance</th></tr></thead><tbody>@forelse($paidSubscriptions as $subscription)@php $paidSummary=$subscriptionSummaries[$subscription->id]; @endphp<tr><td><a href="{{ route('customers.show',$subscription->customer) }}">{{ $subscription->customer->name }}</a><div class="small text-muted">{{ $subscription->customer->primary_mobile }}</div></td><td class="fw-semibold">{{ $subscription->subscription_no }}</td><td>{{ $paidSummary['start_date'] }} – {{ $paidSummary['end_date'] }}</td><td>{{ $paidSummary['package_type'] }}</td><td class="text-end text-success fw-semibold">{{ $currency }}{{ number_format($paidSummary['paid_amount'],2) }}</td><td class="text-end">{{ $currency }}{{ number_format($paidSummary['balance_amount'],2) }}</td></tr>@empty<tr><td colspan="6" class="empty-state">No fully paid subscription accounts found.</td></tr>@endforelse</tbody></table></div></div>
@endif

<div class="card"><div class="table-responsive"><table class="table data-table"><thead><tr><th>Date</th><th>Receipt</th><th>Customer</th><th>Subscription</th><th>Type</th><th>Method</th><th>Recorded by</th><th class="text-end">Amount</th><th class="text-end">Receipt actions</th></tr></thead><tbody>
@forelse($payments as $payment)
<tr><td>{{ $payment->payment_date->format('d M Y') }}</td><td class="fw-semibold"><a href="{{ route('payments.receipt',$payment) }}">{{ $payment->receipt_no }}</a></td><td><a href="{{ route('customers.show', $payment->customer) }}">{{ $payment->customer->name }}</a><div class="small text-muted">{{ $payment->customer->primary_mobile }}</div></td><td>{{ $payment->subscription?->subscription_no ?: '—' }}</td><td><span class="badge {{ $payment->payment_type==='full'?'status-paid':'status-partial' }}">{{ ucfirst($payment->payment_type) }}</span></td><td>{{ ['bank'=>'Bank Transfer','upi'=>'UPI','cash'=>'Cash','card'=>'Card','other'=>'Other'][$payment->method] ?? ucfirst($payment->method) }}</td><td>{{ $payment->creator?->name ?: 'System' }}</td><td class="text-end fw-bold">{{ $currency }}{{ number_format($payment->amount, 2) }}</td><td class="text-end"><div class="dropdown"><button class="btn btn-sm btn-light dropdown-toggle" data-bs-toggle="dropdown">Receipt</button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('payments.receipt',$payment) }}"><i class="bi bi-eye me-2"></i>View Receipt</a><a class="dropdown-item" target="_blank" href="{{ route('payments.receipt.print',$payment) }}"><i class="bi bi-printer me-2"></i>Print Receipt</a><a class="dropdown-item" href="{{ route('payments.receipt.pdf',$payment) }}"><i class="bi bi-file-earmark-pdf me-2"></i>Download PDF</a></div></div></td></tr>
@empty
<tr><td colspan="9" class="empty-state"><i class="bi bi-wallet2 fs-1 d-block mb-2"></i>No payment transactions recorded yet.</td></tr>
@endforelse
</tbody></table></div>@if($payments->hasPages())<div class="card-footer bg-white">{{ $payments->links() }}</div>@endif</div>

<div class="modal fade" id="addPayment" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form method="post" action="{{ route('payments.store') }}" class="modal-content" id="paymentForm">@csrf
    <input type="hidden" name="transaction_token" value="{{ old('transaction_token', $transactionToken) }}">
    <div class="modal-header"><div><h5 class="modal-title">Record payment</h5><small class="text-muted">Add a new ledger transaction without changing previous receipts.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
    <div class="modal-body p-4">
        <label class="form-label">Customer subscription *</label>
        <select name="subscription_id" id="paymentSubscription" class="form-select" required><option value=""></option>
            @foreach($subscriptions as $subscription)
                @php $summary = $subscriptionSummaries[$subscription->id]; @endphp
                <option value="{{ $subscription->id }}" @selected(old('subscription_id', request('subscription'))==$subscription->id)>{{ $summary['customer'] }} - {{ $summary['package_type'] }} - {{ $summary['is_expired'] ? 'Expired '.$summary['expired_days'].' days' : 'Ends '.$summary['end_date'] }} - {{ $summary['payment_status']==='partial'?'Balance':'Due' }} {{ $currency }}{{ number_format($summary['balance_amount'],2) }}</option>
            @endforeach
        </select>
        @if($subscriptions->isEmpty())<div class="alert alert-success mt-3 mb-0"><i class="bi bi-check-circle me-1"></i>No eligible unpaid subscriptions. Enable “Show paid subscriptions” to view completed accounts.</div>@endif

        <div id="paymentCustomerSummary" class="payment-summary d-none mt-3">
            <div class="summary-customer"><div class="avatar" data-summary-initial></div><div><strong data-summary="customer"></strong><span data-summary="mobile"></span></div><span class="badge ms-auto" data-summary-status></span></div>
            <div class="summary-grid"><div><span>Package</span><strong data-summary="package_type"></strong></div><div><span>Selected meals</span><strong data-summary="meals"></strong></div><div><span>Subscription</span><strong><b data-summary="start_date"></b> – <b data-summary="original_end_date"></b></strong></div><div><span>Final extended end</span><strong data-summary="end_date"></strong></div><div><span>Package amount</span><strong data-money="package_amount"></strong></div><div><span>Already paid</span><strong data-money="paid_amount"></strong></div><div><span>Balance due</span><strong class="text-danger" data-money="balance_amount"></strong></div><div><span>Expiry</span><strong data-expiry></strong></div></div>
        </div>
        <div id="subscriptionDueBreakdown" class="due-breakdown d-none mt-3"><div class="d-flex justify-content-between align-items-center mb-2"><strong>Subscription-wise due breakup</strong><small class="text-muted" id="paymentScopeHelp">Full payment is allocated separately across every outstanding subscription.</small></div><div class="table-responsive"><table class="table table-sm mb-2"><thead><tr><th>Subscription</th><th>Period</th><th class="text-end">Package</th><th class="text-end">Paid</th><th class="text-end">Balance</th></tr></thead><tbody id="dueBreakdownRows"></tbody></table></div><div class="due-totals"><div><span id="otherBalanceLabel">Old subscription balance</span><strong id="oldSubscriptionDue">—</strong></div><div><span id="selectedBalanceLabel">New subscription amount</span><strong id="newSubscriptionDue">—</strong></div><div class="grand"><span>Total payable</span><strong id="totalCustomerPayable">—</strong></div></div></div>

        <div class="row g-3 mt-1">
            <div class="col-12"><label class="form-label">Payment type *</label><div class="d-flex gap-2"><input class="btn-check payment-type" type="radio" name="payment_type" value="full" id="paymentFull" @checked(old('payment_type','full')==='full')><label class="btn btn-outline-success flex-fill" for="paymentFull"><i class="bi bi-check-circle me-1"></i>Full payment</label><input class="btn-check payment-type" type="radio" name="payment_type" value="partial" id="paymentPartial" @checked(old('payment_type','full')==='partial')><label class="btn btn-outline-warning flex-fill" for="paymentPartial"><i class="bi bi-pie-chart me-1"></i>Partial payment</label></div></div>
            <div class="col-md-4"><label class="form-label">Payment date *</label><input type="date" name="payment_date" class="form-control" value="{{ old('payment_date', today()->toDateString()) }}" required></div>
            <div class="col-md-4"><label class="form-label">New payment amount *</label><div class="input-group"><span class="input-group-text">{{ $currency }}</span><input type="number" step="0.01" min="0.01" name="amount" id="newPaymentAmount" class="form-control" value="{{ old('amount') }}" required></div></div>
            <div class="col-md-4"><label class="form-label">Payment method *</label><select name="method" class="form-select" required>@foreach(['cash'=>'Cash','upi'=>'UPI','bank'=>'Bank Transfer','other'=>'Other','card'=>'Card'] as $value=>$label)<option value="{{ $value }}" @selected(old('method','cash')===$value)>{{ $label }}</option>@endforeach</select></div>
            <div class="col-12"><div class="balance-preview"><span>Balance after this payment</span><strong id="balanceAfterPayment">—</strong></div></div>
            <div class="col-12 d-none" id="overpaymentWarning"><div class="alert alert-warning mb-0"><strong><i class="bi bi-exclamation-triangle me-1"></i>Overpayment warning</strong><div class="small mb-2">Paid amount is greater than the package amount.</div><div class="form-check"><input type="checkbox" name="confirm_overpayment" value="1" class="form-check-input" id="confirmOverpayment"><label for="confirmOverpayment" class="form-check-label">I confirm this overpayment transaction.</label></div></div></div>
            <div class="col-12"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="3" placeholder="Optional reference or collection note">{{ old('notes') }}</textarea></div>
        </div>
    </div>
    <div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" id="savePayment"><i class="bi bi-receipt me-1"></i>Save transaction</button></div>
</form></div></div>
@endsection

@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><style>.payment-summary{border:1px solid #e7e9ed;border-radius:14px;overflow:hidden}.summary-customer{display:flex;align-items:center;gap:10px;padding:12px 14px;background:#fafbfc}.summary-customer strong,.summary-customer span{display:block}.summary-customer span{font-size:.7rem;color:#777}.summary-grid{display:grid;grid-template-columns:repeat(4,1fr)}.summary-grid>div{padding:11px 13px;border-top:1px solid #eef0f2;border-right:1px solid #eef0f2}.summary-grid span,.summary-grid strong{display:block}.summary-grid span{font-size:.64rem;color:#7c828a}.summary-grid strong{font-size:.77rem;margin-top:3px}.summary-grid b{font-weight:700}.balance-preview{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;background:#f7f8fa;border-radius:10px}.balance-preview span{font-size:.75rem;color:#6f757e}.balance-preview strong{font-size:1.05rem}.select2-container .select2-selection--single{height:43px;border-color:#dfe2e7;border-radius:10px}.select2-container .select2-selection__rendered{line-height:41px!important;padding-left:13px!important}.select2-container .select2-selection__arrow{height:41px!important}@media(max-width:767px){.summary-grid{grid-template-columns:1fr 1fr}}</style>@endpush
@push('styles')<style>.status-overpaid{background:#f3e8ff;color:#7e22ce}</style>@endpush
@push('styles')<style>.due-breakdown{padding:14px;border:1px solid #ead99e;border-radius:14px;background:#fffdf7}.due-breakdown table{font-size:.73rem}.due-breakdown tr.is-selected td{background:#fff6d5;font-weight:700}.due-totals{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.due-totals>div{padding:10px 12px;border:1px solid #e8eaed;border-radius:10px;background:#fff}.due-totals span,.due-totals strong{display:block}.due-totals span{font-size:.64rem;color:#747981}.due-totals strong{font-size:.94rem;margin-top:3px}.due-totals .grand{background:#fff3c5;border-color:#e6c452}.due-totals .grand strong{color:#765400}@media(max-width:767px){.due-breakdown>.d-flex{align-items:flex-start!important;flex-direction:column;gap:3px}.due-totals{grid-template-columns:1fr}}</style>@endpush
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script>
const paymentSummaries=@json($subscriptionSummaries);const paymentCurrency=@json($currency);const paymentSelect=document.getElementById('paymentSubscription');const amountInput=document.getElementById('newPaymentAmount');let selectedPaymentSummary=null;const formatMoney=value=>paymentCurrency+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
$(paymentSelect).select2({dropdownParent:$('#addPayment'),width:'100%',placeholder:'Search customer, mobile, package, or due amount…'}).on('change',syncPaymentSummary);
function renderDueBreakdown(){const box=document.getElementById('subscriptionDueBreakdown'),breakdown=selectedPaymentSummary?.account_breakdown;box.classList.toggle('d-none',!breakdown);if(!breakdown)return;const rows=Array.isArray(breakdown.rows)?breakdown.rows:Object.values(breakdown.rows||{}),selectedId=Number(selectedPaymentSummary.id);document.getElementById('dueBreakdownRows').innerHTML=rows.map(row=>`<tr class="${Number(row.id)===selectedId?'is-selected':''}"><td>${row.subscription_no}${Number(row.id)===selectedId?' <span class="badge text-bg-warning">Selected</span>':''}<small class="d-block text-muted">${row.package_type}</small></td><td>${row.period}</td><td class="text-end">${formatMoney(row.package_amount)}</td><td class="text-end text-success">${formatMoney(row.paid_amount)}</td><td class="text-end text-danger">${formatMoney(row.balance_amount)}</td></tr>`).join('');const selected=rows.find(row=>Number(row.id)===selectedId),otherBalance=rows.filter(row=>Number(row.id)!==selectedId).reduce((sum,row)=>sum+Number(row.balance_amount||0),0),selectedIsLatest=Number(breakdown.latest_subscription_id)===selectedId,hasPaid=Number(selected?.paid_amount||0)>0,hasOther=rows.length>1;document.getElementById('otherBalanceLabel').textContent=selectedIsLatest&&hasOther?'Old subscription balance':'Other subscription balance';document.getElementById('oldSubscriptionDue').textContent=formatMoney(otherBalance);document.getElementById('selectedBalanceLabel').textContent=selectedIsLatest&&hasOther&&!hasPaid?'New subscription amount':'Selected subscription balance';document.getElementById('newSubscriptionDue').textContent=formatMoney(selectedIsLatest&&hasOther&&!hasPaid?selected?.package_amount:selected?.balance_amount);document.getElementById('totalCustomerPayable').textContent=formatMoney(breakdown.total_payable)}
function syncPaymentSummary(){selectedPaymentSummary=paymentSummaries[paymentSelect.value]||null;const card=document.getElementById('paymentCustomerSummary');card.classList.toggle('d-none',!selectedPaymentSummary);document.getElementById('subscriptionDueBreakdown').classList.toggle('d-none',!selectedPaymentSummary);if(!selectedPaymentSummary)return;card.querySelector('[data-summary-initial]').textContent=selectedPaymentSummary.customer.charAt(0).toUpperCase();card.querySelectorAll('[data-summary]').forEach(el=>el.textContent=selectedPaymentSummary[el.dataset.summary]||'—');card.querySelectorAll('[data-money]').forEach(el=>el.textContent=formatMoney(selectedPaymentSummary[el.dataset.money]));const badge=card.querySelector('[data-summary-status]');badge.textContent=selectedPaymentSummary.payment_status.charAt(0).toUpperCase()+selectedPaymentSummary.payment_status.slice(1);badge.className='badge ms-auto status-'+selectedPaymentSummary.payment_status;card.querySelector('[data-expiry]').textContent=selectedPaymentSummary.is_expired?'Expired '+selectedPaymentSummary.expired_days+' day(s)':'Not expired';renderDueBreakdown();syncPaymentType();updateBalance()}
function syncPaymentType(){if(!selectedPaymentSummary)return;const full=document.getElementById('paymentFull').checked,total=Number(selectedPaymentSummary.account_breakdown?.total_payable||selectedPaymentSummary.balance_amount);if(full){amountInput.value=total.toFixed(2);amountInput.readOnly=true}else amountInput.readOnly=false;document.getElementById('paymentScopeHelp').textContent=full?'Full payment is allocated separately across every outstanding subscription.':'Partial payment applies only to the selected subscription.';updateBalance()}function updateBalance(){if(!selectedPaymentSummary){document.getElementById('balanceAfterPayment').textContent='—';return}const full=document.getElementById('paymentFull').checked,startingBalance=full?Number(selectedPaymentSummary.account_breakdown?.total_payable||selectedPaymentSummary.balance_amount):selectedPaymentSummary.balance_amount,amount=Number(amountInput.value||0),remaining=startingBalance-amount;document.getElementById('balanceAfterPayment').textContent=remaining>=0?formatMoney(remaining):formatMoney(Math.abs(remaining))+' overpaid';document.getElementById('balanceAfterPayment').className=remaining<0?'text-danger':remaining===0?'text-success':'';document.getElementById('overpaymentWarning').classList.toggle('d-none',full||remaining>=0)}document.querySelectorAll('.payment-type').forEach(input=>input.addEventListener('change',syncPaymentType));amountInput.addEventListener('input',updateBalance);document.getElementById('paymentForm').addEventListener('submit',function(){document.getElementById('savePayment').disabled=true});syncPaymentSummary();
@if($errors->any())bootstrap.Modal.getOrCreateInstance(document.getElementById('addPayment')).show();@endif
</script>@endpush
