<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $payment->receipt_no }} · Payment Receipt</title>
<style>
@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;background:#f2f3f5;color:#303238;font-family:"DejaVu Sans",Arial,sans-serif;font-size:13px}.actions{max-width:820px;margin:18px auto;display:flex;justify-content:flex-end;gap:8px}.btn{border:0;border-radius:8px;padding:10px 15px;background:#fff;color:#27292d;text-decoration:none;cursor:pointer;font-weight:700;box-shadow:0 2px 8px #0001}.btn.primary{background:#d8a900;color:#fff}.receipt{position:relative;max-width:820px;min-height:1060px;margin:0 auto 24px;background:#fff;padding:42px 48px;overflow:hidden;box-shadow:0 8px 30px #0002}.receipt:before{content:"";position:absolute;inset:0;background-image:radial-gradient(circle,#d8a900 1px,transparent 1.5px);background-size:24px 24px;opacity:.045;pointer-events:none}.content{position:relative}.header{display:flex;justify-content:space-between;gap:30px;padding-bottom:24px;border-bottom:3px solid #d8a900}.brand{display:flex;gap:14px;align-items:flex-start}.logo{width:66px;height:66px;object-fit:contain;border-radius:12px}.logo-fallback{width:66px;height:66px;border-radius:12px;background:#f5c928;color:#3b3000;display:flex;align-items:center;justify-content:center;font-size:22px;font-weight:800}.business h1{font-size:22px;margin:2px 0 7px}.business p{margin:3px 0;color:#656970;max-width:390px;line-height:1.4}.title{text-align:right}.title h2{margin:4px 0 8px;font-size:22px;text-transform:uppercase;letter-spacing:1px}.title .number{color:#8b6a00;font-weight:700}.meta{display:grid;grid-template-columns:1fr 1fr;gap:0 42px;margin:28px 0}.row{display:flex;justify-content:space-between;gap:20px;padding:9px 0;border-bottom:1px solid #ece9df}.row span{color:#6d7076}.row strong{text-align:right}.section-title{margin:24px 0 8px;padding:9px 12px;background:#fff4c6;border-left:4px solid #d8a900;font-size:13px;text-transform:uppercase;letter-spacing:.5px}.amounts{width:100%;border-collapse:collapse}.amounts th,.amounts td{padding:11px 12px;border-bottom:1px solid #ece9df;text-align:right}.amounts th:first-child,.amounts td:first-child{text-align:left}.amounts thead{background:#faf8f0}.amounts .current{background:#fff9df;font-weight:700}.amounts .balance{font-size:16px;color:#9b321f}.status{display:inline-block;padding:5px 10px;border-radius:20px;background:#e7f6ec;color:#20723d;font-weight:700}.notes{min-height:54px;padding:12px;background:#fafafa;border:1px solid #eee;border-radius:8px;line-height:1.5}.footer{display:grid;grid-template-columns:1fr 220px;align-items:end;gap:50px;margin-top:70px}.thanks{font-size:16px;font-weight:700;color:#745900}.printed{margin-top:7px;color:#797d83;font-size:11px}.signature{text-align:center;border-top:1px solid #555;padding-top:8px}.thermal-label{display:none}
body.thermal{background:#fff}.thermal .actions{max-width:80mm}.thermal .receipt{width:80mm;min-height:0;margin:0 auto;padding:8mm 5mm;box-shadow:none;font-size:10px}.thermal .header{display:block}.thermal .title{text-align:left;margin-top:12px}.thermal .meta{grid-template-columns:1fr;gap:0}.thermal .footer{grid-template-columns:1fr;margin-top:35px}.thermal .signature{margin-top:45px}.thermal .thermal-label{display:inline}
@media print{body{background:#fff}.actions{display:none!important}.receipt{box-shadow:none;margin:0;max-width:none;min-height:0;padding:12mm}.receipt:before{-webkit-print-color-adjust:exact;print-color-adjust:exact}body.thermal .receipt{width:80mm;padding:5mm}body.thermal{width:80mm}@page{margin:5mm}}
</style></head><body>
@unless($pdf)<div class="actions no-print"><a class="btn" href="{{ route('payments.index') }}">Back</a><button class="btn" onclick="document.body.classList.add('thermal');window.print();document.body.classList.remove('thermal')">Thermal Print</button><a class="btn" href="{{ route('payments.receipt.pdf',$payment) }}">Download PDF</a><button class="btn primary" onclick="window.print()">Print Receipt</button></div>@endunless
<main class="receipt"><div class="content">
<header class="header"><div class="brand">@if($pdf ? $logoPath : $logoWebUrl)<img class="logo" src="{{ $pdf ? $logoPath : $logoWebUrl }}" alt="Logo">@else<div class="logo-fallback">{{ strtoupper(substr($business['name'],0,2)) }}</div>@endif<div class="business"><h1>{{ $business['name'] }}</h1>@if($business['mobile'])<p>{{ $business['mobile'] }}</p>@endif @if($business['address'])<p>{!! nl2br(e($business['address'])) !!}</p>@endif</div></div><div class="title"><h2>Payment Receipt</h2><div class="number">{{ $payment->receipt_no }}</div></div></header>

<section class="meta"><div><div class="row"><span>Receipt Number</span><strong>{{ $payment->receipt_no }}</strong></div><div class="row"><span>Transaction ID</span><strong style="font-size:10px">{{ $payment->transaction_token ?: '—' }}</strong></div><div class="row"><span>Payment Date</span><strong>{{ $payment->payment_date->format('d-m-Y') }}</strong></div><div class="row"><span>Payment Method</span><strong>{{ ['bank'=>'Bank Transfer','upi'=>'UPI','cash'=>'Cash','card'=>'Card','other'=>'Other'][$payment->method] ?? ucfirst($payment->method) }}</strong></div></div><div><div class="row"><span>Customer</span><strong>{{ $payment->customer->name }}</strong></div><div class="row"><span>Mobile</span><strong>{{ $payment->customer->primary_mobile }}</strong></div><div class="row"><span>Subscription</span><strong>{{ $payment->subscription?->subscription_no ?: '—' }}</strong></div><div class="row"><span>Status</span><strong><span class="status">{{ $paymentStatus }}</span></strong></div></div></section>

<h3 class="section-title">Subscription details</h3><section class="meta" style="margin-top:0"><div><div class="row"><span>Subscription Period</span><strong>{{ $payment->subscription?->start_date?->format('d-m-Y') }} – {{ $payment->subscription?->end_date?->format('d-m-Y') }}</strong></div><div class="row"><span>Package Type</span><strong>{{ $payment->subscription ? str($payment->subscription->package_type)->replace('_',' ')->title() : '—' }}</strong></div></div><div><div class="row"><span>Selected Meals</span><strong>{{ $payment->subscription?->meal_names ?: '—' }}</strong></div><div class="row"><span>Payment Type</span><strong>{{ ucfirst($payment->payment_type) }}</strong></div></div></section>

<h3 class="section-title">Payment summary</h3><table class="amounts"><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody><tr><td>Package Amount</td><td>{{ $currency }}{{ number_format($packageAmount,2) }}</td></tr><tr><td>Previous Paid Amount</td><td>{{ $currency }}{{ number_format($previousPaid,2) }}</td></tr><tr class="current"><td>Current Payment Amount</td><td>{{ $currency }}{{ number_format($payment->amount,2) }}</td></tr><tr><td>Total Paid Amount</td><td>{{ $currency }}{{ number_format($totalPaid,2) }}</td></tr><tr><td><strong>Balance Amount</strong></td><td class="balance">{{ $currency }}{{ number_format($balance,2) }}</td></tr></tbody></table>

<h3 class="section-title">Notes</h3><div class="notes">{{ $payment->notes ?: 'No notes provided.' }}</div>
<footer class="footer"><div><div class="thanks">Thank you for your payment</div><div class="printed">Printed on {{ now()->format('d-m-Y h:i A') }}</div></div><div class="signature">Authorized Signature</div></footer>
</div></main>
@if($autoPrint && !$pdf)<script>window.addEventListener('load',()=>window.print())</script>@endif
</body></html>
