@extends('layouts.app')
@section('title', 'Renew subscription')
@section('content')
@php $currency = \App\Models\Setting::value('currency', '₹'); @endphp
<div class="mb-4"><a href="{{ route('customers.show',$customer) }}" class="small text-decoration-none"><i class="bi bi-arrow-left"></i> {{ $customer->name }}</a><h1 class="page-title mt-2">Renew subscription</h1><p class="page-subtitle">Create a separate subscription beginning after the previous final extended end date.</p></div>

<div class="card mb-4 renewal-breakdown"><div class="card-body"><div class="d-flex align-items-center justify-content-between mb-3"><div><div class="section-title">Subscription-wise payable breakup</div><small class="text-muted">Old dues remain linked to the old subscription and are never merged silently.</small></div>@if($previous)<span class="badge status-{{ $previous->payment_status }}">Previous: {{ $previous->subscription_no }}</span>@endif</div><div class="row g-3"><div class="col-md-4"><div class="breakup-item old"><span>Old subscription balance</span><strong>{{ $currency }}{{ number_format($oldSubscriptionBalance,2) }}</strong>@if($previous)<small>Final end: {{ $previous->end_date->format('d M Y') }}</small>@endif</div></div><div class="col-md-4"><div class="breakup-item new"><span>New subscription amount</span><strong id="renewalNewAmount">{{ $currency }}0.00</strong><small>Recorded against the new subscription</small></div></div><div class="col-md-4"><div class="breakup-item total"><span>Total payable</span><strong id="renewalTotalPayable">{{ $currency }}{{ number_format($oldSubscriptionBalance,2) }}</strong><small>Displayed total; payments remain subscription-specific</small></div></div></div></div></div>

<form method="post" action="{{ route('customers.renew.store',$customer) }}">@csrf<div class="card"><div class="card-body p-4"><div class="alert alert-light border mb-4"><i class="bi bi-info-circle me-1"></i>Renewal starts on or after <strong>{{ \Carbon\Carbon::parse($renewalStartDate)->format('d M Y') }}</strong>. Food after the previous final end date belongs only to this new subscription.</div>@include('customers._subscription',['renewal'=>true])</div><div class="card-footer bg-white p-3 text-end"><a href="{{ route('customers.show',$customer) }}" class="btn btn-light">Cancel</a><button class="btn btn-primary">Create renewal subscription</button></div></div></form>
@endsection
@push('styles')<style>.breakup-item{height:100%;padding:15px;border:1px solid #e8eaed;border-radius:12px;background:#fafbfc}.breakup-item span,.breakup-item strong,.breakup-item small{display:block}.breakup-item span{font-size:.7rem;color:#737982}.breakup-item strong{font-size:1.35rem;margin:5px 0}.breakup-item small{font-size:.65rem;color:#858a91}.breakup-item.old{border-left:3px solid #df8a38}.breakup-item.new{border-left:3px solid #d3a000}.breakup-item.total{background:#fff8df;border-color:#edcf6f}.breakup-item.total strong{color:#795600}</style>@endpush
@push('scripts')<script>const renewalCurrency=@json($currency),oldSubscriptionBalance={{ (float)$oldSubscriptionBalance }};function updateRenewalBreakup(){const amount=Number(document.getElementById('packageAmount')?.value||0);document.getElementById('renewalNewAmount').textContent=renewalCurrency+amount.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});document.getElementById('renewalTotalPayable').textContent=renewalCurrency+(oldSubscriptionBalance+amount).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}document.getElementById('packageAmount')?.addEventListener('input',updateRenewalBreakup);document.querySelectorAll('.meal-input').forEach(input=>input.addEventListener('change',()=>setTimeout(updateRenewalBreakup)));updateRenewalBreakup();</script>@endpush
